direction: right

Robot {
    Keyboard
    Gazebo
}

ROS2Nodes {

  Time_Scheuler {
    ScheulerNode
  }

  RX_Process{
    DirectionNode   
  }
  
  Motioncontroller {
    MotionCtrlNode 
  }

  System {
    DebugMonitor
    UIInterface
  }
}

#message flow
Robot.Keyboard -> RX_Process.DirectionNode : Key_Pressed
Time_Scheuler.ScheulerNode -> RX_Process.DirectionNode : TimeCycle.10ms

RX_Process.DirectionNode -> Motioncontroller.MotionCtrlNode : Direction
Time_Scheuler.ScheulerNode -> Motioncontroller.MotionCtrlNode : TimeCycle.5ms

Motioncontroller.MotionCtrlNode -> Robot.Gazebo : MotionCommand


#Display
#System.UIInterface -> PlanningNodes.GameStateManager
System.DebugMonitor -> All